name: Auto Tag on Special Commits

on:
  push:
    branches: [ main ]

jobs:
  tag-and-build:
    if: contains(github.event.head_commit.message, 'tag')
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push tag

    steps:
      - uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest version tag
        id: get_tag
        run: |
          latest=$(git tag --sort=-v:refname | grep '^v' | head -n 1)
          echo "Latest tag: $latest"
          if [[ -z "$latest" ]]; then
            echo "tag=v1.0.0" >> $GITHUB_OUTPUT
          else
            version=$(echo $latest | sed 's/v//')
            IFS='.' read -r major minor patch <<< "$version"
            patch=$((patch + 1))
            echo "tag=v$major.$minor.$patch" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.get_tag.outputs.tag }}
          git push origin refs/tags/${{ steps.get_tag.outputs.tag }}

